Disabled deprecated protocols
hmcts/jenkins-role pull request #7
Opened 2018-06-19 14:55 UTC by janisBerz

Disabled deprecated protocols to force Slaves to connect over JNLP 4.

2018-06-20 10:40 UTC, ghost submitted a review, later dismissed

2018-06-20 10:54 UTC, kyrian-hmcts requested changes
jenkins_permission_list seems a bit too ambiguous for my liking, can you make it a bit more clearly named?

2018-06-20 10:55 UTC, kyrian-hmcts reviewed
Indeed, haven't you called the variable in  question jenkins_jnlp_disabled_protocols in your other PR?

2018-06-20 13:32 UTC, kyrian-hmcts submitted a review, later dismissed

2018-06-20 13:33 UTC, kyrian-hmcts commented
Tests need to pass before this should be merged though!

2018-06-25 15:44 UTC, fdhmcts approved these changes

2018-06-25 15:54 UTC, merged